// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"flashsale/product-service/internal/adapter/inbound/grpc"
	"flashsale/product-service/internal/adapter/outbound/postgres"
	"flashsale/product-service/internal/application/usecase"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/jmoiron/sqlx"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

// initApp meng-inject seluruh dependensi dari Repository hingga gRPC Server.
func initApp(db *sqlx.DB, logger log.Logger) (*grpc.ProductServiceServer, error) {
	productRepository := postgres.NewProductRepo(db)
	listFlashSaleProductsUsecase := usecase.NewListFlashSaleProductsUsecase(productRepository)
	productServiceServer := grpc.NewProductServiceServer(listFlashSaleProductsUsecase, logger)
	return productServiceServer, nil
}
